### ISSUE TITLE
Add Smart Contract call example

### ISSUE THREAD

**Issue by anchupin** [bnb-chain/greenfield-contracts-sdk#37]
Could you please add example how to call `createSeries` in https://github.com/bnb-chain/greenfield-contracts-sdk/blob/main/contracts/examples/ebook-shop.sol

**Comment by cosinlink** [comment]
you can refer this: https://docs.bnbchain.org/bnb-greenfield/for-developers/cross-chain-integration/demo-contract-as-bucket-owner/

**Comment by anchupin** [comment]
@cosinlink in that case could you also provide same examples for ObjectApp and GroupApp?

**Comment by anchupin** [comment]
@cosinlink have an error on `ExecutorMsg.getSetBucketFlowRateLimitParams`

```
Storage address: 0xF2cB204F02ce3A1d3e69Da0F0aFe8AD95FFCDd72
RangeError: "length" is outside of buffer bounds
    at Buffer.proto.utf8Write (node:internal/buffer:1066:13)
    at Op.writeStringBuffer [as fn] (/Users/andrew/Code/Store/store-contracts/node_modules/protobufjs/src/writer_buffer.js:61:13)
    at BufferWriter.finish (/Users/andrew/Code/Store/store-contracts/node_modules/protobufjs/src/writer.js:453:14)
    at Function.ExecutorMsg.getSetBucketFlowRateLimitParams (/Users/andrew/Code/Store/store-contracts/node_modules/@bnb-chain/src/client/executor/message.ts:66:49)
    at test (/Users/andrew/Code/Store/store-contracts/scripts/altdev.ts:27:52)
    at processTicksAndRejections (node:internal/process/task_queues:105:5) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```


```
const creator = await attachContract<GreenfieldDemo>("GreenfieldDemo", "0xF2cB204F02ce3A1d3e69Da0F0aFe8AD95FFCDd72")
    console.log("Storage address:", await creator.getAddress())

    const address = await creator.getAddress();
    const dataSetBucketFlowRateLimit = ExecutorMsg.getSetBucketFlowRateLimitParams({
        bucketName: "blabla3",
        bucketOwner: address,
        operator: address,
        paymentAddress: address,
        flowRateLimit: '1000000000000000000',
    });
```

**Comment by anchupin** [comment]
@cosinlink is there any difference between using IBucketHub and BucketApp for bucket creation?
For me that block of code below looks a bit weird. Do I actually the owner of bucket in that case? Why should I give permission to upload files If I'm the owner(or is that permission only for cross-chain upload???)?
 
<img width="763" alt="image" src="https://github.com/user-attachments/assets/4951c86a-be37-4659-aca2-5d056505b2b9">

**Comment by anchupin** [comment]
@cosinlink about an error above `RangeError: "length" is outside of buffer bounds`

Everything is OK, the problem was with NodeJS in version 22.7.0, updated to 22.8.0, now it's OK

**Comment by AndrewChupin** [comment]
@cosinlink have some problems with object creation.

I have a bucket:
https://testnet.greenfieldscan.com/bucket/0x00000000000000000000000000000000000000000000000000000000000048b7?tab=object

But I can't grant permission to the owner. I'm trying:
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/e9c97893-02de-4cc8-a724-7a68c51f5ed4">
Transaction is successful - https://testnet.bscscan.com/tx/0xca4d43ed445ab94b4ea7cf8d1eef56e65896c6f2733adf6e56e7486bb691d480

But when I'm trying to create the object I see an error - `Error: Query failed with (6): rpc error: code = Unknown desc = failed to execute message; message index: 0: The creator(0x7eeE0E672244f9f199C4d5B644D4351d14ee7D41) has no CreateObject permission of the bucket(blabla3): Access denied`
